In [1]:
import pandas as pd
import numpy as np
import torch

In [4]:
nv = np.array([[1,2,3,4],
               [5,6,7,8]])
print(nv)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
nvt = nv.T
print(nvt)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [6]:
nv1 = torch.tensor([[1,2,3,4],
                    [5,6,7,8]])
print(nv1)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [7]:
nvt1 = nv1.T
print(nvt1)

tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
