# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[ 2.3   2.    3.93 -2.61  1.29]
 [-2.01 -1.97 -2.74  0.98 -0.68]
 [ 0.06  0.71 -1.99  3.86 -1.68]]
 
[[-0.05 -0.94  1.73 -1.04]
 [-1.24 -0.66  1.64 -0.95]
 [-0.21 -0.89  1.75 -1.  ]
 [-1.3   3.27 -5.91  3.27]
 [-4.54  2.56 -3.88  1.85]
 [ 0.16  0.93 -1.83  1.03]
 [-2.23  0.05  0.48 -0.39]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ') # Pytorch tensor * numpy ndarray
print(np.round( A@C2  ,2))

tensor([[ 1.6300,  0.4400, -0.6300,  0.1400, -2.0600, -0.1100, -1.4200],
        [ 0.3300,  1.3500, -1.1500, -0.8400, -0.8200, -1.0900,  0.3700],
        [-0.1900,  0.7000, -0.6100, -0.2200, -1.2400, -0.6600,  1.0800]],
       dtype=torch.float64)
 
tensor([[ 1.6300,  0.4400, -0.6300,  0.1400, -2.0600, -0.1100, -1.4200],
        [ 0.3300,  1.3500, -1.1500, -0.8400, -0.8200, -1.0900,  0.3700],
        [-0.1900,  0.7000, -0.6100, -0.2200, -1.2400, -0.6600,  1.0800]])
