In [1]:
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

%matplotlib inline

In [2]:
!curl -k -o helper_functions.py https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 10246  100 10246    0     0  36753      0 --:--:-- --:--:-- --:--:-- 37123


In [3]:
from helper_functions import create_tensorboard_callback, plot_loss_curves, unzip_data, walk_through_dir

In [4]:
walk_through_dir("10_food_classes_10_percent")

There are 2 directories and 0 images in '10_food_classes_10_percent'.
There are 10 directories and 0 images in '10_food_classes_10_percent\test'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\chicken_curry'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\chicken_wings'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\fried_rice'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\grilled_salmon'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\hamburger'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\ice_cream'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\pizza'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\ramen'.
There are 0 directories and 250 images in '10_food_classes_10_percent\test\steak'.
There are 0 directories and 250 images in '10_food_classes_10_percent

In [5]:
train_dir = "10_food_classes_10_percent/train"
test_dir = "10_food_classes_10_percent/test"

In [6]:
IMG_SIZE = (224, 224)

train_data_10_percent = tf.keras.preprocessing.image_dataset_from_directory(
    train_dir,
    label_mode='categorical',
    batch_size=32,
    image_size=IMG_SIZE,
    shuffle=True
)

test_data_10_precent = tf.keras.preprocessing.image_dataset_from_directory(
    test_dir,
    label_mode='categorical',
    batch_size=32,
    image_size=IMG_SIZE,
    shuffle=True
)

Found 750 files belonging to 10 classes.
Found 2500 files belonging to 10 classes.


In [7]:
train_data_10_percent

<BatchDataset element_spec=(TensorSpec(shape=(None, 224, 224, 3), dtype=tf.float32, name=None), TensorSpec(shape=(None, 10), dtype=tf.float32, name=None))>

In [8]:
train_data_10_percent.class_names

['chicken_curry',
 'chicken_wings',
 'fried_rice',
 'grilled_salmon',
 'hamburger',
 'ice_cream',
 'pizza',
 'ramen',
 'steak',
 'sushi']

In [9]:
for images, labels in train_data_10_percent.take(1): # Take Takes the Number of batches that you mention EX. 1 in this case
  print(images, labels)

tf.Tensor(
[[[[1.31983261e+02 9.99832611e+01 6.19832611e+01]
   [1.31620529e+02 9.96205368e+01 6.15703125e+01]
   [1.30332596e+02 9.83325882e+01 5.94051323e+01]
   ...
   [8.60078125e+01 6.37220993e+01 3.10546894e+01]
   [1.02529022e+02 7.92555847e+01 4.86004486e+01]
   [1.04805809e+02 8.31149597e+01 5.50535736e+01]]

  [[1.21924103e+02 8.99241028e+01 5.02566948e+01]
   [1.18416290e+02 8.64162903e+01 4.72712021e+01]
   [1.17314728e+02 8.53147278e+01 4.44575882e+01]
   ...
   [8.95111542e+01 6.64966507e+01 2.27544594e+01]
   [9.08660583e+01 6.77946320e+01 2.59352570e+01]
   [1.12661827e+02 9.08772278e+01 4.87767792e+01]]

  [[1.19351562e+02 8.83515625e+01 4.39229927e+01]
   [1.20353798e+02 8.93537979e+01 4.49252243e+01]
   [1.22967636e+02 9.19676361e+01 4.75390625e+01]
   ...
   [8.98448639e+01 7.18236618e+01 2.04497757e+01]
   [8.59241028e+01 6.88593750e+01 1.89006691e+01]
   [8.62734375e+01 7.02075882e+01 1.70636139e+01]]

  ...

  [[2.46000000e+02 2.51000000e+02 2.45000000e+02]
   [2

In [ ]:
base_model = tf.keras.applications.EfficientNetV2B0(include_top=False)

base_model.trainable = False

inputs = tf.keras.layers.Input(shape = (224, 224, 3), name = "Input_Layer")

x = base_model(inputs)

x = tf.keras.layers.GlobalAveragePooling2D(name = "global_average_pooling_layer")(x) # (x) is to pass the previos "x" named layer as input

outputs = tf.keras.layers.Dense(10, activation = "softmax", name = "output_layer")(x)

model_0 = tf.keras.Model(inputs, outputs)