In [1]:
import tensorflow as tf

In [2]:
tensor_zero_dimensional = tf.constant(4) # Using .constant() to create a zero dimensional vector 
print(tensor_zero_dimensional)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_dimensional = tf.constant([1,2,3,4,5]) # Using .constant(   [...]   ) to create a one dimensional vector 
print(tensor_one_dimensional)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [4]:
tensor_one_dimensional = tf.constant([1,2,3,4,5.]) # Using .constant(    [...]    ) to create a one dimensional vector 
print(tensor_one_dimensional)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [5]:
tensor_two_dimensional = tf.constant([
    [1,2,3,4,5],
    [6,7,8,9,10]
    ]) # Using .constant(   [    [...], [...]    ]    ) to create a two dimensional vector 
print(tensor_two_dimensional)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [6]:

tensor_three_dimensional = tf.constant(
    [
        [   # First 2D array
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10]
        ],
        [   # Second 2D array
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10]
        ]
    ]
)
# Using .constant(     [     [  [...], [...]  ], [  [...], [...]  ]     ]     ) to create a three dimensional vector 
print(tensor_three_dimensional)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]], shape=(2, 2, 5), dtype=int32)


In [7]:
l = [tensor_zero_dimensional.ndim, tensor_one_dimensional.ndim, tensor_two_dimensional.ndim, tensor_three_dimensional.ndim]
l

[0, 1, 2, 3]

In [8]:
tensor_one_dimensional = tf.constant([1,2,3,4,5.], dtype = tf.float32) 
tensor_one_dimensional = tf.cast(tensor_one_dimensional, dtype = tf.int16) 
# Cast method can change the dtype of the tensor
print(tensor_one_dimensional)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int16)


In [9]:
tensor_bool = tf.constant([True, False, True])
casted_tensor_bool = tf.cast(tensor_bool, dtype = tf.int16)
casted_tensor_bool

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 0, 1], dtype=int16)>

In [10]:
tensor_string = tf.constant(["Hello", "World"])
tensor_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Hello', b'World'], dtype=object)>

In [11]:
import numpy as np

In [12]:
np_array = np.array([1,2,3,4])
converted_tensor = tf.convert_to_tensor(np_array)
converted_tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [13]:
# Use the .eye() function to create an identity matrix
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=None,
    batch_shape=None,
    dtype=tf.float32,
    name=None,
)

eye_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [14]:
# Use the .eye() function to create an identity matrix
eye_tensor_bool = tf.eye(
    num_rows = 5,
    num_columns=None,
    batch_shape=None,
    dtype=tf.bool,
    name=None,
)

eye_tensor_bool

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])>

In [15]:
# Use the .eye() function to create an identity matrix
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[3],
    dtype=tf.int32,
    name=None,
)

eye_tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])>

In [16]:
fill_tensor = tf.fill(dims = [3,5], value = 9, name=None, layout=None)
fill_tensor

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])>

In [17]:
ones_tensor = tf.ones(shape = [5,3], dtype=tf.float32, name=None, layout=None)
ones_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
ones_like_tensor = tf.ones_like(fill_tensor)
ones_like_tensor

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [19]:
zeros_tensor = tf.zeros(shape = [5,3], dtype=tf.float32, name=None, layout=None)
zeros_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [20]:
zeros_like_tensor = tf.zeros_like(fill_tensor)
zeros_like_tensor

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [21]:
zeros_like_tensor.shape

TensorShape([3, 5])

In [22]:
tf.shape(zeros_like_tensor) # shape = (2, )

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5])>

In [23]:
tf.rank(zeros_like_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [24]:
tf.size(zeros_like_tensor) # Size = 15

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [25]:
random_tensor = tf.random.normal(
    shape = [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None,
)
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.2566372 , -1.1396443 ],
       [ 0.02446574, -0.22933859],
       [ 0.7483923 ,  0.18490826]], dtype=float32)>

In [26]:
random_tensor_uniform = tf.random.uniform(
    shape = [5,3],
    minval=0,
    maxval=100,
    dtype=tf.float32,
    seed=None,
    name=None,
)
random_tensor_uniform

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[72.447845 , 60.205795 , 36.918427 ],
       [11.475968 , 42.354893 , 29.615105 ],
       [55.14251  , 43.00376  , 13.032842 ],
       [67.86127  , 53.155327 ,  1.1221766],
       [50.677917 , 60.631157 , 12.646079 ]], dtype=float32)>

In [27]:
tf.random.set_seed(42)
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=42,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=42,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=42,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=42,name=None))

tf.Tensor(
[[41.63028 ]
 [26.858162]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[16.06157 ]
 [88.118576]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[91.72338 ]
 [99.724106]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[78.463554]
 [35.660732]], shape=(2, 1), dtype=float32)


In [28]:
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=41,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=41,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=41,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=41,name=None))

tf.Tensor(
[[32.075645]
 [62.67551 ]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[19.502281]
 [54.075386]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[ 4.6827674]
 [64.59448  ]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[96.50926 ]
 [ 9.065187]], shape=(2, 1), dtype=float32)


In [29]:
tensor_indexed = tf.constant([0,1,2,3,4,5,6,7,8,9])
print(tensor_indexed[2])

tf.Tensor(2, shape=(), dtype=int32)


In [30]:
tensor_indexed = tf.constant([[0, 1, 2, 3, 4],
                               [5, 6, 7, 8, 9],
                               [10, 11, 12, 13, 14]])
print(tensor_indexed[0][2])

tf.Tensor(2, shape=(), dtype=int32)


In [31]:
print(tensor_indexed[:,4])

tf.Tensor([ 4  9 14], shape=(3,), dtype=int32)


In [32]:
print(tensor_indexed[...,4])

tf.Tensor([ 4  9 14], shape=(3,), dtype=int32)


In [33]:
print(tensor_indexed[2,...])

tf.Tensor([10 11 12 13 14], shape=(5,), dtype=int32)


In [34]:
x = tf.constant([0, -1, 2, -3, 4])
print(tf.abs(x))

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [35]:
x = tf.constant(3+4j)
print(tf.abs(x))

tf.Tensor(5.0, shape=(), dtype=float64)


In [36]:
x_1 = tf.constant([[5,3,6,6,4,6]], dtype = tf.float32)
x_2 = tf.constant([[7], [5], [3]], dtype = tf.float32)

print(x_1.shape)
print(x_2.shape)
print(tf.math.multiply(x_1, x_2))

(1, 6)
(3, 1)
tf.Tensor(
[[35. 21. 42. 42. 28. 42.]
 [25. 15. 30. 30. 20. 30.]
 [15.  9. 18. 18. 12. 18.]], shape=(3, 6), dtype=float32)


In [37]:
x_argmax = tf.constant([[2, 20, 30, 3, 6],
                        [3, 11, 16, 1, 8],
                        [14, 45, 23, 5, 27]])

print(x_argmax.shape)
print(tf.math.argmin(x_argmax, axis = 1))

(3, 5)
tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [38]:
x_argmax = tf.constant([200, 120, 130, 3, 6])
print(tf.math.argmax(x_argmax))

tf.Tensor(0, shape=(), dtype=int64)


In [39]:
tensor_two_d = tf.constant([[1,-2,0],
                            [3,5,100],
                            [1,5,6],
                            [2,3,8]], dtype = tf.float16)
print(tensor_two_d.shape)

print(tf.math.reduce_std(tensor_two_d, axis=0, keepdims=True, name=None))

(4, 3)
tf.Tensor([[ 0.829  2.861 41.38 ]], shape=(1, 3), dtype=float16)


In [40]:
tf.math.top_k(tensor_two_d, k = 2)

TopKV2(values=<tf.Tensor: shape=(4, 2), dtype=float16, numpy=
array([[  1.,   0.],
       [100.,   5.],
       [  6.,   5.],
       [  8.,   3.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[0, 2],
       [2, 1],
       [2, 1],
       [2, 1]])>)

In [41]:
x_1 = tf.constant([[1,2,0]])

x_2 = tf.constant([[1,2],
                  [3,5],
                  [4,5]])

x_3 = tf.constant([[1,2,0,2],
                  [3,5,-1,2]])

print(x_1.shape, x_2.shape, x_3.shape, tf.transpose(x_2).shape)
# x_3.T = 4,2
# x_2.T = 2,3
print(tf.transpose(x_3)@tf.transpose(x_2))
tf.linalg.matmul(
    x_3, x_2, transpose_a=True, transpose_b=True, adjoint_a=False, adjoint_b=False,
    a_is_sparse=False, b_is_sparse=False, output_type=None, name=None
)

(1, 3) (3, 2) (2, 4) (2, 3)
tf.Tensor(
[[ 7 18 19]
 [12 31 33]
 [-2 -5 -5]
 [ 6 16 18]], shape=(4, 3), dtype=int32)


<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7, 18, 19],
       [12, 31, 33],
       [-2, -5, -5],
       [ 6, 16, 18]])>