In [2]:
import tensorflow as tf

In [3]:
tensor_zero_dimensional = tf.constant(4) # Using .constant() to create a zero dimensional vector 
print(tensor_zero_dimensional)

tf.Tensor(4, shape=(), dtype=int32)


In [4]:
tensor_one_dimensional = tf.constant([1,2,3,4,5]) # Using .constant(   [...]   ) to create a one dimensional vector 
print(tensor_one_dimensional)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


In [5]:
tensor_one_dimensional = tf.constant([1,2,3,4,5.]) # Using .constant(    [...]    ) to create a one dimensional vector 
print(tensor_one_dimensional)

tf.Tensor([1. 2. 3. 4. 5.], shape=(5,), dtype=float32)


In [6]:
tensor_two_dimensional = tf.constant([
    [1,2,3,4,5],
    [6,7,8,9,10]
    ]) # Using .constant(   [    [...], [...]    ]    ) to create a two dimensional vector 
print(tensor_two_dimensional)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)


In [7]:

tensor_three_dimensional = tf.constant(
    [
        [   # First 2D array
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10]
        ],
        [   # Second 2D array
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10]
        ]
    ]
)
# Using .constant(     [     [  [...], [...]  ], [  [...], [...]  ]     ]     ) to create a three dimensional vector 
print(tensor_three_dimensional)

tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[ 1  2  3  4  5]
  [ 6  7  8  9 10]]], shape=(2, 2, 5), dtype=int32)


In [8]:
l = [tensor_zero_dimensional.ndim, tensor_one_dimensional.ndim, tensor_two_dimensional.ndim, tensor_three_dimensional.ndim]
l

[0, 1, 2, 3]

In [9]:
tensor_one_dimensional = tf.constant([1,2,3,4,5.], dtype = tf.float32) 
tensor_one_dimensional = tf.cast(tensor_one_dimensional, dtype = tf.int16) 
# Cast method can change the dtype of the tensor
print(tensor_one_dimensional)

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int16)


In [10]:
tensor_bool = tf.constant([True, False, True])
casted_tensor_bool = tf.cast(tensor_bool, dtype = tf.int16)
casted_tensor_bool

<tf.Tensor: shape=(3,), dtype=int16, numpy=array([1, 0, 1], dtype=int16)>

In [11]:
tensor_string = tf.constant(["Hello", "World"])
tensor_string

<tf.Tensor: shape=(2,), dtype=string, numpy=array([b'Hello', b'World'], dtype=object)>

In [12]:
import numpy as np

In [13]:
np_array = np.array([1,2,3,4])
converted_tensor = tf.convert_to_tensor(np_array)
converted_tensor

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [14]:
# Use the .eye() function to create an identity matrix
eye_tensor = tf.eye(
    num_rows = 5,
    num_columns=None,
    batch_shape=None,
    dtype=tf.float32,
    name=None,
)

eye_tensor

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [15]:
# Use the .eye() function to create an identity matrix
eye_tensor_bool = tf.eye(
    num_rows = 5,
    num_columns=None,
    batch_shape=None,
    dtype=tf.bool,
    name=None,
)

eye_tensor_bool

<tf.Tensor: shape=(5, 5), dtype=bool, numpy=
array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])>

In [16]:
# Use the .eye() function to create an identity matrix
eye_tensor = tf.eye(
    num_rows = 3,
    num_columns=None,
    batch_shape=[3],
    dtype=tf.int32,
    name=None,
)

eye_tensor

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]],

       [[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]]])>

In [17]:
fill_tensor = tf.fill(dims = [3,5], value = 9, name=None, layout=None)
fill_tensor

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])>

In [18]:
ones_tensor = tf.ones(shape = [5,3], dtype=tf.float32, name=None, layout=None)
ones_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [19]:
ones_like_tensor = tf.ones_like(fill_tensor)
ones_like_tensor

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])>

In [20]:
zeros_tensor = tf.zeros(shape = [5,3], dtype=tf.float32, name=None, layout=None)
zeros_tensor

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [21]:
zeros_like_tensor = tf.zeros_like(fill_tensor)
zeros_like_tensor

<tf.Tensor: shape=(3, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])>

In [22]:
zeros_like_tensor.shape

TensorShape([3, 5])

In [23]:
tf.shape(zeros_like_tensor) # shape = (2, )

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5])>

In [24]:
tf.rank(zeros_like_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [25]:
tf.size(zeros_like_tensor) # Size = 15

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [26]:
random_tensor = tf.random.normal(
    shape = [3,2],
    mean=0.0,
    stddev=1.0,
    dtype=tf.float32,
    seed=None,
    name=None,
)
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.7866283 , -0.9625913 ],
       [-0.9936956 ,  0.26558354],
       [ 0.22440223, -1.1494738 ]], dtype=float32)>

In [27]:
random_tensor_uniform = tf.random.uniform(
    shape = [5,3],
    minval=0,
    maxval=100,
    dtype=tf.float32,
    seed=None,
    name=None,
)
random_tensor_uniform

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[19.105446, 55.198524, 10.493159],
       [78.2998  ,  9.708845, 67.64982 ],
       [13.953233, 49.995922, 36.262165],
       [51.211403, 64.935196, 71.114815],
       [ 5.490029, 53.182198, 60.419094]], dtype=float32)>

In [28]:
tf.random.set_seed(42)
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=42,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=42,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=42,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=42,name=None))

tf.Tensor(
[[41.63028 ]
 [26.858162]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[16.06157 ]
 [88.118576]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[91.72338 ]
 [99.724106]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[78.463554]
 [35.660732]], shape=(2, 1), dtype=float32)


In [29]:
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=41,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=41,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=41,name=None))
print(tf.random.uniform(shape = [2,1],minval=0,maxval=100,dtype=tf.float32,seed=41,name=None))

tf.Tensor(
[[32.075645]
 [62.67551 ]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[19.502281]
 [54.075386]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[ 4.6827674]
 [64.59448  ]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[96.50926 ]
 [ 9.065187]], shape=(2, 1), dtype=float32)


In [30]:
tensor_indexed = tf.constant([0,1,2,3,4,5,6,7,8,9])
print(tensor_indexed[2])

tf.Tensor(2, shape=(), dtype=int32)


In [37]:
tensor_indexed = tf.constant([[0, 1, 2, 3, 4],
                               [5, 6, 7, 8, 9],
                               [10, 11, 12, 13, 14]])
print(tensor_indexed[0][2])

tf.Tensor(2, shape=(), dtype=int32)


In [41]:
print(tensor_indexed[:,4])

tf.Tensor([ 4  9 14], shape=(3,), dtype=int32)


In [42]:
print(tensor_indexed[...,4])

tf.Tensor([ 4  9 14], shape=(3,), dtype=int32)


In [43]:
print(tensor_indexed[2,...])

tf.Tensor([10 11 12 13 14], shape=(5,), dtype=int32)


In [44]:
x = tf.constant([0, -1, 2, -3, 4])
print(tf.abs(x))

tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)


In [45]:
x = tf.constant(3+4j)
print(tf.abs(x))

tf.Tensor(5.0, shape=(), dtype=float64)
